### ISSUE TITLE
Make Description Conventions in ld4p:RT:bf2:AdminMetadata:BFDB repeatable

### ISSUE THREAD

**Issue by NancyL** [LD4P/ld4ptemplates#17]
Cataloging may use multiple description conventions, e.g., RDA & DCRM Books or RDA & DACS. The field should be repeatable

**Comment by NancyL** [comment]
Any comments on this?

**Comment by NancyJean** [comment]
I agree it should be repeatable.  In addition to traditional cataloging conventions, would this be where we'd enter other RDF vocabs/conventions/models that we're using to extend BF?  e,g,, dct, prov-O, DPLA, Europeana, etc.

**Comment by gracianipicardo** [comment]
Agree. I don't see a reason to keep this as a non-repeatable value and will affect communities using more than one content standard
