### ISSUE TITLE
Agents profile has fields with nested RTs of same type; Sinopia does not like

### ISSUE THREAD

**Issue by michelleif** [LD4P/ld4ptemplates#20]
In the profile https://github.com/LD4P/ld4ptemplates/blob/master/LD4P%20BIBFRAME%202.0%20Agents.json (id: ld4p:profile:bf2:Agents:Attributes), there are 3 Resource Templates where there's a situation that Sinopia doesn't like:

a field (property template) of type Resource nests more than one Resource Template with the same resourceURI

(this is sort of like the situation where you have multiple property templates with the same propertyURI; Sinopia doesn't know where to put the information after it's saved and you want to see it again in the template)

in Resource Template ld4p:RT:bf2:Agent:Person, the field "Address of Corporate Body (RDA 11.9)" refers to 2 templates with the same resourceURI:  
 "ld4p:RT:bf2:Agents:Addresses", 
"ld4p:RT:bf2:Agents:Addresses:Extended"

in Resource Template ld4p:RT:bf2:Agent:CorporateBody, the field "Address of Corporate Body (RDA 11.9)" refers to 2 templates with the same resourceURI:   
"ld4p:RT:bf2:Agents:Addresses", 
"ld4p:RT:bf2:Agents:Addresses:Extended"

in Resource Template ld4p:RT:bf2:Agent:Conference, the field "Place Associated with Conference (RDA 11.3) CORE ELEMENT" refers to 2 templates with the same resourceURI:    
"ld4p:RT:bf2:Agents:RWO:LocationOfConference",   
 "ld4p:RT:bf2:Agents:RWO:OtherPlace"

**Comment by NancyL** [comment]
fixing this by removing everything but type of agent and lookups
