### ISSUE TITLE
Rare Materials profile has a field with nested RTs of same type; Sinopia does not like

### ISSUE THREAD

**Issue by gracianipicardo** [LD4P/ld4ptemplates#27]
The resource templates (RT) "ld4p:RT:bf2:RareMat:Work", "ld4p:RT:bf2:RareMat:Instance" and "ld4p:RT:bf2:RareMat:Item" include a property template Form of [Work/Instance/Item] (bf:genreForm) that nest three RTs with the same resourceURI (bf:GenreForm). This profile construction is not accepted by Sinopia data validation.

The nested RTs with same resourceURI are:

"ld4p:RT:bf2:RareMat:AAT",
"ld4p:RT:bf2:Form",
"ld4p:RT:bf2:RareMat:RBMS"

**Comment by gracianipicardo** [comment]
*Suggested approach* -> change property "Form of [Work/Instance/Item]" from type = Resource to type = Lookup, since QA handles AAT and LCGFT. For RBMS, direct catalogers to copy and paste RBMS concepts URI from https://rbmsvocabs.github.io/ while the QA service gets implemented.

**Comment by eslao** [comment]
Any timeframe for a possible fix? This issue affects templates that Harvard is building out for incunables. Thanks!

**Comment by gracianipicardo** [comment]
Potential fix -- change the property Form to type lookup since AAT and LCGFT are already in QA. For RBMS, there is a request pending to add https://rbmsvocabs.github.io/ to QA, but catalogers could copy/paste the concept URI in the meantime. Added a sample of this solution to DEV for testing (https://development.sinopia.io/editor/ld4p:RT:bf2:RareMat:Work). @mmcgee, @NancyL, @NancyJean, could you provide feedback on this?

**Comment by dezel002** [comment]
Minnesota is also eager for a fix on this. We are unable to proceed on our workplan without a usable Rare Materials template
