### ISSUE TITLE
RT "ld4p:RT:bf2:RareMat:Instance" has a field with nested RTs of same type; Sinopia does not like

### ISSUE THREAD

**Issue by gracianipicardo** [LD4P/ld4ptemplates#28]
The RT "ld4p:RT:bf2:RareMat:Instance" include a property template "References and Related Instances"(bflc:relationship) that nests 2 RTs with the same resourceURI (bflc:Relationship). This profile construction is not accepted by Sinopia data validation.

The nested RTs with same resourceURI are:

"ld4p:RT:bf2:RareMat:RefWork"
"ld4p:RT:bf2:RelatedInstance"

*NOTE* - This validation error is similar to #27, but opening a new issue because we might need a different approach

**Comment by mmcgee** [comment]
Wondering if there has been any progress on figuring out a fix for this.  The Harvard Incunables project is hoping to implement the RareMat Instance template soon.  Thanks.

**Comment by gracianipicardo** [comment]
This looks like an ontology limitation for the description of rare materials, since BIBFRAME doesn't have a specific class for citations, and the LoC Rare Materials profile uses bflc:Relationship class for both Reference Sources and Related materials. We could start exploring the integration of the ARM modeling recommendation for [Bibliographic citations](https://github.com/LD4P/arm/blob/master/modeling_recommendations/bibliographic_citations.md) on the ld4p rare materials profile, or figure out a different way of modeling the current use of bflc:Relationship. A potential fix using just one bflc:Relationship RT that combines both uses as citation and related resource has been uploaded to DEV (https://development.sinopia.io/editor/ld4p:RT:bf2:RareMat:Instance) for your review, @mmcgee, @NancyL , @NancyJean

**Comment by NancyL** [comment]
Somehow this issue has gone away now we fixed issue 27. It also looks correct to me. Paloma is trying to figure out why it fixed itself.

**Comment by gracianipicardo** [comment]
On December 2019, the validation error given by Sinopia was the following:

<img width="543" alt="Capture" src="https://user-images.githubusercontent.com/46054906/72475906-88ad0180-37b1-11ea-8880-b013396caac0.PNG">

The current profile still includes a bflc:relationship property type=Resource that calls to 2 RTs with class bflc:Relationship. Any chance that this has to do with an update in the Sinopia validation rules @michelleif , @jermnelson ?

**Comment by michelleif** [comment]
Hi Paloma,

Yes this is due to Sinopia validation rules, it's not anything new, it's just that I didn't document it. It's the same type of problem as having two fields in the same template that both use the same property URI; when re-opening a saved template, Sinopia won't know which field to put the information into (https://github.com/LD4P/sinopia/wiki/Why-Sinopia-doesn't-allow-repeated-propertyURIs-in-a-single-Resource-Template).

So from an Instance you want to refer to both Related Instances and References? Are References places where the Instance is cited? Or Works that the Instance refers to?

Michelle

________________________________

**Comment by gracianipicardo** [comment]
@michelleif it is the first case, titles that cite the instance being described. 

This issue was opened because Sinopia was not validating the property calling to two+ RTs with the same class URI. For some reason, the validation error doesn't show anymore, even though the property has not been updated: https://stage.sinopia.io/editor/ld4p:RT:bf2:RareMat:Instance

**Comment by michelleif** [comment]
I just opened it on stage and saw the error.

**Comment by gracianipicardo** [comment]
Suggesting to use bflc:indexedIn instead of bflc:relationship to link the Instance with the related work, following the Serials Affinity Group modeling proposal. Test RT uploaded to Sinopia dev: https://development.sinopia.io/editor/ld4p:RT:bf2:RareMat:Instance

**Comment by gracianipicardo** [comment]
Fixed
