### ISSUE TITLE
Add bf:ClassificationNlm to all (nested and unnested) _Monograph Work templates

### ISSUE THREAD

**Issue by NancyJean** [LD4P/ld4ptemplates#29]
in re ld4p:RT:bf2:Monograph:Work and ld4p:RT:bf2:Monograph:Work:Un-nested

Please add bf:ClassificationNlm to the Class subtemplate in the  _Monograph Work templates in Sinopia.  It is in the _Serials Work template if you need a modeling example.  I thought it had been added to an earlier version of the Monograph Work template, but is now gone.
 
This is a work stoppage for NLM and I don't believe it warrants creating a custom Work template for NLM.

**Comment by NancyJean** [comment]
so I saw that this was done for the nested mono profile (thank you!), but not for the un-nested one.

**Comment by gracianipicardo** [comment]
bf:ClassificationNlm has been added to both Monograph Work RTs (nested and un-nested). Pull requests are pending.

Templates can be checked on Sinopia Dev
- Nested: https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work
- Un-nested: https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested
